[[Account]]
    Username = "u@somewhere.com"
    Password = "password0"
    EnableSSL = true
    [Account.IncomingMailServer]
        Hostname = "imap.somewhere.com"
        Port = 993
    [Account.OutgoingMailServer]
        Hostname = "smtp.somewhere.com"
        Port = 465

[[Account]]
    Username = "u@somewhere.net"
    Password = "password1"
    EnableSSL = true
    SkipCertificateVerification = true
    [Account.IncomingMailServer]
        Hostname = "imap.somewhere.net"
        Port = 993
    [Account.OutgoingMailServer]
        Hostname = "smtp.somewhere.net"
        Port = 465