[[mailbox]]
username = "u@example.com"
password = "somepassword0"
enableSSL = true
    [mailbox.incomming]
    hostname = "imap.example.com"
    port = 123
    [mailbox.outgoing]
    hostname = "smtp.example.com"
    port = 456

[[mailbox]]
username = "u@example.net"
password = "somepassword1"
enableSSL = false
    [mailbox.incomming]
    hostname = "imap.example.net"
    port = 789
    [mailbox.outgoing]
    hostname = "smtp.example.net"
    port = 233